// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfEaATg4MZFUm-pC67eJGMGZLWIyRlxg0',
    appId: '1:54331985752:web:aca6a3da10512745de1f2d',
    messagingSenderId: '54331985752',
    projectId: 'see-for-me-a8e66',
    authDomain: 'see-for-me-a8e66.firebaseapp.com',
    storageBucket: 'see-for-me-a8e66.appspot.com',
    measurementId: 'G-4JWB8XFYC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoYGo1u7nEUTQVqf2hS11NZ2UEK6hLJo',
    appId: '1:54331985752:android:044cbb2047e133d5de1f2d',
    messagingSenderId: '54331985752',
    projectId: 'see-for-me-a8e66',
    storageBucket: 'see-for-me-a8e66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvn9tVUYIq7W69Uc3Li_90Nrm8iVutwkU',
    appId: '1:54331985752:ios:036053e2e5f8a200de1f2d',
    messagingSenderId: '54331985752',
    projectId: 'see-for-me-a8e66',
    storageBucket: 'see-for-me-a8e66.appspot.com',
    iosBundleId: 'seeforme.app.seeForMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvn9tVUYIq7W69Uc3Li_90Nrm8iVutwkU',
    appId: '1:54331985752:ios:036053e2e5f8a200de1f2d',
    messagingSenderId: '54331985752',
    projectId: 'see-for-me-a8e66',
    storageBucket: 'see-for-me-a8e66.appspot.com',
    iosBundleId: 'seeforme.app.seeForMe',
  );
}
